# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DownloaderDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

platform :ios, '8.0'
pod 'ARSLineProgress', '~> 2.0'

  # Pods for DownloaderDemo

  target 'DownloaderDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DownloaderDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
